version: "3.9"

services:
  api:
    build: .
    container_name: shrc_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "31009:8000"
    networks:
      - shrc-bridge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/openapi.json"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  shrc-bridge:
    external: true
